client_config_backend: file
client_config:
    client_id: 146502376979-dr7titiegr9us5r1e63e7lmklrldvvl5.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/drive.install